"""Builds the Journeys listing and one page per journey from journeys.json.

    python super-travel/build.py

Writes journeys/index.html and journeys/<slug>/index.html, and refreshes the cards
in index.html between its <!-- journeys:start --> and <!-- journeys:end --> markers.
The nav, footer, chat URL and favicon are copied from index.html, so change those
there and run this again. Edit journeys.json for content, never the generated pages.

Every page links styles.css and main.js as ?v=<hash of both files>, so a browser that cached
an older copy fetches the new one. Run this after editing styles.css or main.js too.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from html import escape
from pathlib import Path
from typing import Any, Dict, List

SITE = Path(__file__).parent
DATA = SITE / "journeys.json"
INDEX = SITE / "index.html"

IMAGE = "https://images.unsplash.com/photo-{id}?auto=format&fit=crop&w={w}&h={h}&q=80"
SETTING_CLASS = {"Outdoor": "out", "Indoor": "in", "Mixed": "mix"}
COUNT_WORDS = ["Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine", "Ten"]
MARKERS = re.compile(r"<!-- journeys:start -->.*?<!-- journeys:end -->", re.S)
CARD_INDENT = " " * 10
GENERATED = "<!-- Generated by build.py from journeys.json. Edit those, not this file. -->"
ARROW = (
    '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2" '
    'stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 12h14M13 6l6 6-6 6"/></svg>'
)

Journey = Dict[str, Any]


def esc(text: object) -> str:
    return escape(str(text), quote=True)


def fail(message: str) -> "SystemExit":
    return SystemExit(f"build.py: {message}")


def money(site: Dict[str, Any], amount: int) -> str:
    return f"{site['currency']}{amount:,}"


def load() -> Dict[str, Any]:
    site = json.loads(DATA.read_text(encoding="utf-8"))
    seen = set()
    for j in site["journeys"]:
        if j["slug"] in seen:
            raise fail(f"duplicate slug {j['slug']!r}")
        seen.add(j["slug"])
        rows = j.get("budget_breakdown") or []
        if rows and sum(r["amount"] for r in rows) != j["budget"]:
            raise fail(f"{j['slug']}: budget_breakdown adds up to {sum(r['amount'] for r in rows)}, not {j['budget']}")
        for day in j["itinerary"]:
            if day["setting"] not in SETTING_CLASS:
                raise fail(f"{j['slug']}: setting {day['setting']!r} must be one of {sorted(SETTING_CLASS)}")
        if len(j["itinerary"]) != j["days"]:
            raise fail(f"{j['slug']}: says {j['days']} days but lists {len(j['itinerary'])}")
    return site


# --- Shared pieces, copied from index.html so there is one source for them -----

def grab(pattern: str, text: str, what: str) -> re.Match:
    found = re.search(pattern, text, re.S)
    if not found:
        raise fail(f"index.html: could not find the {what}")
    return found


def asset_version() -> str:
    digest = hashlib.sha1()
    for name in ("styles.css", "main.js"):
        digest.update((SITE / name).read_bytes())
    return digest.hexdigest()[:10]


def read_shell(index_html: str) -> Dict[str, str]:
    return {
        "version": asset_version(),
        "chat_url": grab(r'<meta name="chat-url" content="([^"]*)">', index_html, "chat-url meta tag").group(1),
        "favicon": grab(r'<link rel="icon" href="[^"]*">', index_html, "favicon link").group(0),
        "nav": grab(r'<header class="nav">.*?</header>', index_html, "<header class=\"nav\">").group(0),
        "footer": grab(r'<footer class="footer".*?</footer>', index_html, "<footer class=\"footer\">").group(0),
    }


def relink(fragment: str, root: str) -> str:
    """Make index.html's relative links work from a page `root` levels down. Same-page and external links stay."""
    def fix(m: re.Match) -> str:
        url = m.group(1)
        if url in ("#", "#contact") or re.match(r"(https?:|mailto:)", url):
            return m.group(0)
        return f'href="{root}{url}"'
    return re.sub(r'href="([^"]*)"', fix, fragment)


def page(shell: Dict[str, str], *, title: str, description: str, root: str, body: str) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{esc(title)}</title>
  <meta name="chat-url" content="{esc(shell['chat_url'])}">
  <meta name="description" content="{esc(description)}">
  <script>document.documentElement.classList.add('js');</script>
  {shell['favicon']}
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=League+Spartan:wght@300;400;500;600;700;800;900&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="{root}styles.css?v={shell['version']}">
</head>
<body>
{GENERATED}

  {relink(shell['nav'], root)}

{body}

  {relink(shell['footer'], root)}

  <script src="{root}main.js?v={shell['version']}"></script>
</body>
</html>
"""


# --- Cards (home page and listing) ---------------------------------------------

def title_html(title: str) -> str:
    """'Goa, Unhurried' becomes 'Goa,<br><em>unhurried</em>', the site's heading style."""
    head, _, last = title.rpartition(" ")
    return f"{esc(head)}<br><em>{esc(last.lower())}</em>" if head else esc(title)


def card_tags(site: Dict[str, Any], j: Journey) -> List[str]:
    return [f"{j['days']} days"] + ([money(site, j["budget"])] if j["budget"] else []) + j["tags"]


def card(site: Dict[str, Any], j: Journey, href: str, index: int, level: int) -> str:
    delay = ' style="--d:120ms"' if index % 2 else ""
    tags = "".join(f"<li>{esc(t)}</li>" for t in card_tags(site, j))
    # "View Journey" is the card's one link; it covers the photo, so the photo is clickable too.
    return f"""<article class="case reveal"{delay}>
  <div class="case__media">
    <img src="{IMAGE.format(id=j['image'], w=1000, h=1333)}" alt="{esc(j['alt'])}" loading="lazy" width="1000" height="1333">
    <a class="case__view" href="{href}" aria-label="View journey: {esc(j['title'])}"><span>View<br>Journey</span></a>
  </div>
  <div class="case__meta">
    <p class="case__cat">{esc(j['category'])}</p>
    <h{level} class="case__title">{esc(j['title'])}</h{level}>
    <ul class="case__tags">{tags}</ul>
  </div>
</article>"""


def indent(text: str, prefix: str) -> str:
    return "\n".join(prefix + line if line else line for line in text.splitlines())


def home_cards(site: Dict[str, Any]) -> str:
    cards = "\n\n".join(card(site, j, f"journeys/{j['slug']}/", i, 3) for i, j in enumerate(site["journeys"]))
    return indent(cards, CARD_INDENT)


def refresh_index(index_html: str, site: Dict[str, Any], version: str) -> str:
    if not MARKERS.search(index_html):
        raise fail("index.html: journeys:start / journeys:end markers are missing")
    block = f"<!-- journeys:start -->\n{home_cards(site)}\n{CARD_INDENT}<!-- journeys:end -->"
    refreshed = MARKERS.sub(lambda _: block, index_html, count=1)
    refreshed = re.sub(r'href="styles\.css(\?v=\w+)?"', f'href="styles.css?v={version}"', refreshed)
    return re.sub(r'src="main\.js(\?v=\w+)?"', f'src="main.js?v={version}"', refreshed)


# --- Listing page ----------------------------------------------------------------

def crumbs(items: List[tuple]) -> str:
    """items: (label, href or None); the last one is the current page."""
    lis = "".join(
        f'<li><a href="{href}">{esc(label)}</a></li>' if href else f'<li aria-current="page">{esc(label)}</li>'
        for label, href in items
    )
    return f'<nav aria-label="Breadcrumb"><ol class="crumbs reveal">{lis}</ol></nav>'


def listing_page(shell: Dict[str, str], site: Dict[str, Any]) -> str:
    cards = "\n\n".join(card(site, j, f"{j['slug']}/", i, 2) for i, j in enumerate(site["journeys"]))
    count = len(site["journeys"])
    count_word = COUNT_WORDS[count] if count < len(COUNT_WORDS) else str(count)
    body = f"""  <main id="top">
    <section class="work work--page">
      <div class="container">
        {crumbs([("Home", "../"), ("Journeys", None)])}

        <div class="section-head section-head--split reveal">
          <div>
            <p class="eyebrow">Journeys</p>
            <h1 class="display section-title">All<br><em>journeys</em></h1>
          </div>
          <p class="section-note">{count_word} trips we have arranged recently, each built around the season, the forecast, and the budget. Open one to see it day by day.</p>
        </div>

        <div class="work__grid">
{indent(cards, CARD_INDENT)}
        </div>
      </div>
    </section>
  </main>"""
    return page(
        shell,
        title="Journeys — GlobeTrot",
        description=f"{count_word} journeys arranged by GlobeTrot, each planned around the season, the forecast and the budget.",
        root="../",
        body=body,
    )


# --- Journey page ----------------------------------------------------------------

def facts(site: Dict[str, Any], j: Journey) -> str:
    rows = [
        ("Duration", f"{j['days']} days"),
        ("Budget", money(site, j["budget"]) if j["budget"] else "Set by you"),
        ("Best season", j["season"]),
        ("Stay", j["stay"]),
    ]
    return "".join(f"<div><dt>{label}</dt><dd>{esc(value)}</dd></div>" for label, value in rows)


def budget_table(site: Dict[str, Any], j: Journey) -> str:
    rows = j.get("budget_breakdown") or []
    if not rows:
        return ""
    body = "".join(f'<tr><th scope="row">{esc(r["label"])}</th><td>{money(site, r["amount"])}</td></tr>' for r in rows)
    return f"""
          <table class="budget">
            <caption>Where the {money(site, j['budget'])} goes</caption>
            <tbody>{body}</tbody>
            <tfoot><tr><th scope="row">Total</th><td>{money(site, j['budget'])}</td></tr></tfoot>
          </table>"""


def day_rows(j: Journey) -> str:
    return "\n".join(
        f"""          <li class="dayrow reveal">
            <span class="dayrow__num">Day {n:02d}</span>
            <div>
              <h3>{esc(d['title'])}</h3>
              <p>{esc(d['text'])}</p>
            </div>
            <span class="setting setting--{SETTING_CLASS[d['setting']]}">{esc(d['setting'])}</span>
          </li>"""
        for n, d in enumerate(j["itinerary"], start=1)
    )


def journey_page(shell: Dict[str, str], site: Dict[str, Any], index: int) -> str:
    journeys = site["journeys"]
    j = journeys[index]
    prev, nxt = journeys[index - 1], journeys[(index + 1) % len(journeys)]
    overview = "\n          ".join(f'<p class="body-copy">{esc(p)}</p>' for p in j["overview"])
    notes = "".join(f"<div><dt>{esc(n['label'])}</dt><dd>{esc(n['text'])}</dd></div>" for n in j["notes"])
    body = f"""  <main id="top">
    <section class="jhero">
      <div class="container">
        {crumbs([("Home", "../../"), ("Journeys", "../"), (j['title'], None)])}
        <p class="case__cat reveal">{esc(j['category'])}</p>
        <h1 class="display jtitle reveal">{title_html(j['title'])}</h1>

        <div class="jhero__row grid-12">
          <p class="jhero__lede reveal">{esc(j['lede'])}</p>
          <dl class="facts reveal" style="--d:120ms">{facts(site, j)}</dl>
        </div>

        <figure class="jhero__image reveal">
          <img src="{IMAGE.format(id=j['image'], w=1800, h=1012)}" alt="{esc(j['alt'])}" width="1800" height="1012">
        </figure>
      </div>
    </section>

    <section class="jbody">
      <div class="container grid-12 jbody__grid">
        <div class="jbody__text reveal">
          <p class="eyebrow">The journey</p>
          {overview}
        </div>
        <aside class="jbody__aside reveal" style="--d:120ms" aria-label="Good to know">
          <h2 class="aside__head">Good to know</h2>
          <dl class="notes">{notes}</dl>{budget_table(site, j)}
        </aside>
      </div>
    </section>

    <section class="jdays" aria-labelledby="days-title">
      <div class="container">
        <div class="section-head reveal">
          <p class="eyebrow">Day by day</p>
          <h2 class="display section-title" id="days-title">The<br><em>itinerary</em></h2>
        </div>
        <ol class="days">
{day_rows(j)}
        </ol>
      </div>
    </section>

    <section class="cta">
      <div class="container cta__inner">
        <div class="reveal">
          <h2 class="display cta__title">Want a trip<br><em>like this?</em></h2>
          <p class="cta__note">Tell the concierge where, for how long and what you would like to spend. It checks the forecast and builds the itinerary around it.</p>
        </div>
        <a class="btn-pill reveal" style="--d:120ms" href="#contact" data-chat-link data-chat-journey="{j['slug']}">Plan a trip</a>
      </div>
    </section>

    <nav class="pager" aria-label="More journeys">
      <div class="container pager__inner">
        <a class="pager__link reveal" href="../{prev['slug']}/"><span>Previous journey</span><strong>{esc(prev['title'])}</strong></a>
        <a class="pager__link pager__link--next reveal" style="--d:120ms" href="../{nxt['slug']}/"><span>Next journey</span><strong>{esc(nxt['title'])}</strong></a>
      </div>
    </nav>
  </main>"""
    return page(shell, title=f"{j['title']} — GlobeTrot", description=j["lede"], root="../../", body=body)


# --- Build -----------------------------------------------------------------------

def render_all() -> Dict[Path, str]:
    """Every file this script owns, as {path: contents}."""
    site = load()
    index_html = INDEX.read_text(encoding="utf-8")
    shell = read_shell(index_html)
    files = {INDEX: refresh_index(index_html, site, shell["version"]), SITE / "journeys" / "index.html": listing_page(shell, site)}
    for i, j in enumerate(site["journeys"]):
        files[SITE / "journeys" / j["slug"] / "index.html"] = journey_page(shell, site, i)
    return files


def main() -> int:
    for path, text in render_all().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        before = path.read_text(encoding="utf-8") if path.exists() else None
        if before != text:
            with path.open("w", encoding="utf-8", newline="\n") as out:
                out.write(text)
        print(f"{'wrote    ' if before != text else 'unchanged'} {path.relative_to(SITE)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
